[package]
name = "bball-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4.0"
rand = "0.9.2"
rand_distr = "0.5.1"
serde = {version = "1.0.228", features = ["derive"]}
strum = "0.27.2"
strum_macros = "0.27.2"
